### ISSUE TITLE
improve error discovery for missing data values

### ISSUE THREAD

**Issue by cppforlife** [k14s/kapp-controller#10]
> Error message:

```
    Stderr:      kapp: Error: Validation errors:
- Expected 'kind' on resource '/ () cluster' to be non-empty (stdin doc 10)
- Expected 'apiVersion' on resource '/ () cluster' to be non-empty (stdin doc 10)
- Expected 'metadata.name' on resource '/ () cluster' to be non-empty (stdin doc 10)
```

> Okay, this took a long time and was pretty much trial and error, would love to find some way to possibly make that easier.  My secret that I was using for inline.pathsFrom with the ytt section didn't have #@data/values at the top.

**Comment by voor** [comment]
App CR looked like this:

```yaml
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: deploy
  namespace: kapp-controller
spec:
  fetch:
  - git:
      url: https://github.com/voor/cluster-api-gitops
      ref: origin/master
      subPath: workload/deploy
  template:
  - ytt:
      ignoreUnknownComments: true
      inline:
        pathsFrom:
        - secretRef:
            name: initial-values
  deploy:
  - kapp: {}
```

The secret with the error *initially* looked like this:

```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: initial-values
  namespace: kapp-controller
stringData:
  values2.yml: |
    acme_email: rcvanvo@gmail.com
    github_client_id: REMOVED
    github_client_secret: REMOVED
    grafana_client_id: REMOVED
    grafana_client_secret: REMOVED
    sonarqube_client_id: 
    sonarqube_client_secret:
```
Which is incorrect syntax, it should look like this:

```yaml,diff
---
apiVersion: v1
kind: Secret
metadata:
  name: initial-values
  namespace: kapp-controller
stringData:
  values2.yml: |
+    #@data/values
+    ---
    acme_email: rcvanvo@gmail.com
    github_client_id: REMOVED
    github_client_secret: REMOVED
    grafana_client_id: REMOVED
    grafana_client_secret: REMOVED
    sonarqube_client_id: 
    sonarqube_client_secret:
```
