### ISSUE TITLE
Docker powered templates

### ISSUE THREAD

**Issue by Nitive** [k14s/kapp-controller#13]
It would be nice to be able to run any docker image as a template engine.

Configuration may looks like this:

```yaml
# ...
spec:
  # ...
  template:
    - docker:
        image: my-renderer:v1
        values:
          some-value: 123
        valuesFrom:
          - secretRef:
              name: secret-name
          - configMapRef:
              name: configmap-name
```

Have you considered something like this?
