### ISSUE TITLE
Allow kapp-controller to change context to another cluster

### ISSUE THREAD

**Issue by voor** [k14s/kapp-controller#7]
/kind feature

As a user, I would like to concile an App CR deployed in Cluster A into Cluster B, to support a few use cases:

1. I run a central shared services cluster (A) and want to deploy agents into Cluster B
1. I am running a Cluster API provider in cluster (A) and want all of the managed clusters (B... C...) to have applied to them specific capabilities after they are created.

Given a secret of the form:
```
apiVersion: v1
data:
  value: YXBpVmVyc... (base64 encoded kubeconfig file)
kind: Secret
metadata:
  name: another-kubeconfig
  namespace: some-namespace
type: Opaque
```

I can put into the App CR:
```
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: my-app-to-another
  namespace: some-namespace
spec:
  context: 
   -  secretRef:
      name: another-kubeconfig
      subPath: value
   -  secretRef:
      matchLabels:
        somelabel: on-mysecrets
      subPath: value
  fetch:
  - git:
...
  template:
  - ytt: {}
  deploy:
  - kapp: {}
```

Update 1: removed namespace reference so that you can only reference a secret in the same namespace.
Update 2: change context to an array allowing you to define multiple contexts

**Comment by cppforlife** [comment]
tweaked it a bit more

```yaml
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: my-app-to-another
  namespace: some-namespace
spec:
  clusterContext: 
    secretRef:
      name: cluster1
      key: value # (default)
```

i think supporting deploy to multiple clusters is wanted, however, i think it should be done via higher level CRD. for example: 

```yaml
apiVersion: kappctrl.k14s.io/v1alpha1
kind: AppDeployment
metadata:
  name: my-app-to-another
  namespace: some-namespace
spec:
  clusterContext:
    secretRefs:
      matchLabels:
        cluster-creds: ""
  template:
    ...embedded AppSpec from 'kind: App'...
status:
  matchedClusterContexts:
  - name: 
  conditions:
  - type: ReconcileSucceeded
```
