### ISSUE TITLE
Is there a way to reduce permissions required for kapp-controller-cluster-role?

### ISSUE THREAD

**Issue by bryanl** [k14s/kapp-controller#9]
Could it be possible to supply a service account in the App resource that would be used to run kapp rather than giving kapp-controller cluster-admin privileges?

**Comment by cppforlife** [comment]
yup, this came up before from discussions. i think it makes to add a way to use a particular service account for the deploy per app crd.

**Comment by cppforlife** [comment]
@vijaykatam since the time this issue was filed we've added a feature to allow App CR to deploy app to a different cluster via spec.cluster configuration: https://github.com/k14s/kapp-controller/commit/0a1cc95b28c4e4497e5ef84aa9b8530736255bb1#diff-86d5b52d04d712578c1b92ca954a999f. Conceptually this is similar to this feature request since we just need to target current cluster and use given service account for auth. 

i think your breakdown makes sense. 

> 1 is going to be breaking change so I am trying to understand what the guidance here is. 

i was thinking to add a flag to kapp-controller binary itself to require individual service accounts vs allowing use of default service account. we can release two separate installation yamls with these two variations (eventually just deprecate one).

> Add a validation admission controller to validate that the user creating the App CR has read permissions to the service account so that we don't allow specifying arbitrary service account.

hmm, im not sure its good to tie App CR permissions to the "creator" of the resource. instead we can simply scope access to service accounts in the same namespace where app cr resides. this is what we do for configmap/secrets already, and that's what i believe is done for regular Pod's spec.serviceAccount configuration. thoughts on this?

**Comment by vijaykatam** [comment]
> we've added a feature to allow App CR to deploy app to a different cluster via spec.cluster configuration: 0a1cc95#diff-86d5b52d04d712578c1b92ca954a999f

I had a discussion with @bryanl about this today and the desire is to keep kapp-controller app management local to a cluster and our usage is also going to be deploy kapp-controller to every cluster. Additionally I am not sure how one can go about effectively configuring and managing kapp-controller RBAC for external clusters.

> i was thinking to add a flag to kapp-controller binary itself

+1 on this approach

> im not sure its good to tie App CR permissions to the "creator" of the resource

I don't think I was proposing that. Let me explain my line of thought with an example.
```
kind: App
metadata:
  name: fluent-bit
  namespace: tmc-extension-management
spec:
  fetch:
    - image:
        url: foo
  template:
    - ytt:
        paths:
            - foobar
            - foobarbaz
        inline:
          pathsFrom:
            - secretRef:
                name: secret
  deploy:
    - kapp:
        intoNs: tanzu-system-logging
        serviceAccount: tanzu-system-logging
```
For a user to create the App CR above, the admission controller would immediately validate and reject if the account does not have permissions to access the serviceAccount specified, it does not really tie App CR permissions to user account. Since my proposal relies on kapp-controller being able to access service accounts across namespaces this validation prevents privilege escalation by specifying service account a user may not have access to.

>instead we can simply scope access to service accounts in the same namespace where app cr resides

This probably does not work for the use case I outlined above where the app gets deployed to a different namespace.
